import { TextureLoader } from "three";
import type { Texture } from "three";
import { applyPixelFilter } from "./pixelArt";
import { resolveEnemyTexture } from "./enemyTextures";

// Texture cache for the QTE accomplice — the second armed figure that OWNS the
// player-directed fire in peak-difficulty duels (F4 / ADR-0036). Its own tiny
// cache (mirroring hostageTextures.ts): the accomplice is not a shootable window
// archetype, so its art lives beside the hostage at assets/hostage/<key>.png
// (levelArt.json `hostages` block, generated by scripts/gen-hostage-sprites.mjs
// in CI). Until that dedicated art lands, every pose falls back to the captor's
// cop sprite via resolveEnemyTexture("hostage_taker", …) — the same pure
// data-swap seam the captor uses (resolveCaptorTexture in HostageQteSprite). Two
// poses: a gun-lowered IDLE and a gun-raised AIM (the wind-up / firing beat),
// mirroring the enemy idle/shooting split so the fallback carries the
// muzzle-raise tell for free. FLAGGED to lead-art: the accomplice needs its OWN
// sprite family later — the cop fallback is a placeholder.
const loader = new TextureLoader();
const cache = new Map<string, Texture>();
const failed = new Set<string>();
// In-flight loads: getAccompliceTexture runs per rendered frame, so without this
// guard every frame re-issues the same request until a callback lands.
const pending = new Set<string>();

const base = import.meta.env.BASE_URL;
const IDLE_FILE = `${base}assets/hostage/accomplice.png`;
const AIM_FILE = `${base}assets/hostage/accomplice_aim.png`;

function ensureLoaded(file: string): void {
  if (cache.has(file) || failed.has(file) || pending.has(file)) return;
  pending.add(file);
  loader.load(
    file,
    (t) => {
      pending.delete(file);
      cache.set(file, applyPixelFilter(t));
    },
    undefined,
    () => {
      pending.delete(file);
      failed.add(file);
    },
  );
}

/**
 * The accomplice texture for the requested pose (`aiming` = the gun-raised
 * wind-up/firing beat, else the gun-lowered idle). Returns the dedicated sprite
 * once its PNG has decoded, otherwise the captor's cop fallback for the same beat
 * (the shooting cop while aiming, the idle cop otherwise) so the second gun is
 * never an untextured square. `null` only until even the fallback has decoded.
 */
export function getAccompliceTexture(aiming: boolean): Texture | null {
  const file = aiming ? AIM_FILE : IDLE_FILE;
  ensureLoaded(file);
  const own = cache.get(file);
  if (own !== undefined) return own;
  return resolveEnemyTexture("hostage_taker", 1, aiming, 1)?.texture ?? null;
}
