import { TextureLoader } from "three";
import type { Texture } from "three";
import { applyPixelFilter } from "./pixelArt";
import levelArt from "@game/levels/levelArt.json";

// Texture cache for the QTE boss figure — "le Commandant" (ADR-0051/0052/0053,
// chef of the BAC de nuit). Its OWN tiny cache (mirroring hostageTextures.ts /
// courierTextures.ts), NOT enemyTextures: the Commandant is a QTE-only plein-pied
// authority figure that lives BESIDE `enemies` in levelArt.json (the `boss` block),
// never an enemy archetype popping from windows. His canon poses live at
// assets/boss/commander_<pose>.png (generated by the CI art lane). No global
// fallback HERE — the consumer (BossQteSprite) falls back to the committed riot-cop
// sprite while a pose returns null (still loading, or not yet generated).
//
// The two Niveau-Final hall props (lustre, speaker_wall) are generated too and are
// exposed via getBossDecorTexture; the interactive décor-prop draw stays a procedural
// grey placeholder until the render is given a data key selecting which prop to draw
// (no such key in `bossQteSpec.decorProp` today — game-logic lane), so those getters
// are wired-ready seams.
const loader = new TextureLoader();
const cache = new Map<string, Texture>();
const failed = new Set<string>();
// In-flight loads: the resolver runs per rendered frame, so without this guard every
// frame re-issues the same request until a callback lands.
const pending = new Set<string>();

const base = import.meta.env.BASE_URL;

// The canon commander poses that map the core QTE + differentiation states. Keys are
// the `boss.types` entries in levelArt.json; the render maps CURRENT state → pose.
export type BossPose =
  | "shielded"
  | "exposed"
  | "weakpoint"
  | "parry_windup"
  | "hit"
  | "finisher"
  | "down";

// Asset paths sourced from the single source of truth (levelArt.json `boss` block) so a
// renamed/re-pathed asset tracks here without a second edit. A missing entry collapses to
// null (the caller then draws its riot-cop fallback).
const BOSS_TYPES: Record<string, { readonly asset: string } | undefined> = levelArt.boss.types;

function fileForPose(pose: BossPose): string | null {
  const entry = BOSS_TYPES[`commander_${pose}`];
  return entry !== undefined ? `${base}${entry.asset}` : null;
}

function ensureLoaded(file: string): void {
  if (cache.has(file) || failed.has(file) || pending.has(file)) return;
  pending.add(file);
  loader.load(
    file,
    (t) => {
      pending.delete(file);
      cache.set(file, applyPixelFilter(t));
    },
    undefined,
    () => {
      pending.delete(file);
      failed.add(file);
    },
  );
}

/**
 * The Commandant's texture for a given canon pose, or null while it is loading or until
 * that PNG is generated/committed (the caller then draws its riot-cop fallback figure).
 */
export function getBossPoseTexture(pose: BossPose): Texture | null {
  const file = fileForPose(pose);
  if (file === null) return null;
  ensureLoaded(file);
  return cache.get(file) ?? null;
}

/**
 * A Niveau-Final hall décor prop texture (lustre / speaker_wall), or null while loading /
 * ungenerated. Wired-ready: the interactive décor-prop draw stays a procedural grey
 * placeholder until `bossQteSpec.decorProp` carries a key selecting which prop to render
 * (game-logic lane), at which point this getter feeds the prop mesh directly.
 */
export function getBossDecorTexture(kind: "lustre" | "speaker_wall"): Texture | null {
  const entry = BOSS_TYPES[kind];
  if (entry === undefined) return null;
  const file = `${base}${entry.asset}`;
  ensureLoaded(file);
  return cache.get(file) ?? null;
}
