import { TextureLoader } from "three";
import type { Texture } from "three";
import { applyPixelFilter } from "./pixelArt";

// Texture cache for the QTE hostage figures (ADR-0030) — the cartel boss's
// daughter the captor holds in front of him. Deliberately its OWN tiny cache
// (mirroring courierTextures.ts), not enemyTextures: the hostage is not an
// enemy archetype, her art lives at assets/hostage/<key>.png (levelArt.json
// `hostages` block, generated by scripts/gen-hostage-sprites.mjs in CI). No
// global fallback here — the consumer (HostageQteSprite) falls back to the
// committed civilian sprite while this returns null.
const loader = new TextureLoader();
const cache = new Map<string, Texture>();
const failed = new Set<string>();
// In-flight loads: getHostageGirlTexture runs per rendered frame, so without
// this guard every frame re-issues the same request until a callback lands.
const pending = new Set<string>();

const base = import.meta.env.BASE_URL;
const GIRL_FILE = `${base}assets/hostage/girl.png`;

function ensureLoaded(file: string): void {
  if (cache.has(file) || failed.has(file) || pending.has(file)) return;
  pending.add(file);
  loader.load(
    file,
    (t) => {
      pending.delete(file);
      cache.set(file, applyPixelFilter(t));
    },
    undefined,
    () => {
      pending.delete(file);
      failed.add(file);
    },
  );
}

/**
 * The hostage girl's texture, or null while it is loading or until her PNG is
 * generated/committed (the caller then draws its own fallback figure).
 */
export function getHostageGirlTexture(): Texture | null {
  ensureLoaded(GIRL_FILE);
  return cache.get(GIRL_FILE) ?? null;
}
