#!/usr/bin/env python3
"""Build the muf harness infographics — one standalone HTML poster per harness.

Sibling posters to docs/diagrams/agents-pipeline-infographic.html, sharing its
visual system (fanzine B&W + acid neon, light/dark themes) and the pixel-art
crew sprites (docs/diagrams/crew/*.png, generated by muf-crew-bitmap.py).

Each harness gets one self-contained page (no external deps, relative sprite
paths) written to docs/diagrams/harness-<slug>-infographic.html:

  - level-art          — HARNESS.md : génération IA des fonds + render farm
  - window-alignment   — align-windows.mjs / ADR-0028
  - dynamic-verify     — ADR-0005 (Accepted (amended))
  - shared-lib         — ADR-0007 (Accepted)

Run: python3 docs/diagrams/build-harness-infographics.py
"""
import os

OUT_DIR = os.path.dirname(os.path.abspath(__file__))


def sprite(slug, cls="", alt=None):
    alt = alt or slug
    c = f"sprite {cls}".strip()
    return f'<span class="{c}"><img src="crew/{slug}.png" alt="{alt}" /></span>'


# ── Shared head + design system (matches agents-pipeline-infographic.html) ──────
HEAD = """<!doctype html>
<html lang="fr">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--
      muf — infographie de harness (poster HTML autonome).
      Généré par docs/diagrams/build-harness-infographics.py à partir de
      HARNESS.md / docs/adr/*. Sprites : docs/muf-crew-bitmap.py --singles → ./crew/*.png.
      Un poster de la série des infographies muf (cf. agents-pipeline-infographic.html).
    -->
    <title>__TITLE__</title>
    <style>
      :root {
        --paper: #f2efe8; --paper-2: #e9e5da; --ink: #17150f; --ink-soft: #4a4738;
        --line: #17150f; --acid: #b6ff00; --acid-ink: #5f7a00;
        --a1: #0e6e91; --a1-bg: #d8ecf4;   /* bleu — tooling/CI */
        --a2: #c4006b; --a2-bg: #fadbeb;   /* magenta — art/render */
        --a3: #1f7a3d; --a3-bg: #dff0d9;   /* vert — data/manifeste */
        --a4: #b54a00; --a4-bg: #fbe4d2;   /* orange — CI/farm */
        --gate: #8a6d00; --gate-bg: #fff3c4;
        --warn: #a3341a; --warn-bg: #fbe0d8;
        --card: #faf8f3; --shadow: rgba(23, 21, 15, 0.85); --noise: rgba(23, 21, 15, 0.05);
      }
      @media (prefers-color-scheme: dark) {
        :root {
          --paper: #101013; --paper-2: #17171b; --ink: #ececdf; --ink-soft: #a5a293;
          --line: #ececdf; --acid: #b6ff00; --acid-ink: #b6ff00;
          --a1: #3fc3e8; --a1-bg: #0d2530;
          --a2: #ff4fa8; --a2-bg: #2c0f1f;
          --a3: #4fd07d; --a3-bg: #10271a;
          --a4: #ff9a4d; --a4-bg: #2b1a0c;
          --gate: #ffd94d; --gate-bg: #292109;
          --warn: #ff8a66; --warn-bg: #2c1109;
          --card: #17171b; --shadow: rgba(182, 255, 0, 0.28); --noise: rgba(236, 236, 223, 0.04);
        }
      }
      :root[data-theme="light"] {
        --paper: #f2efe8; --paper-2: #e9e5da; --ink: #17150f; --ink-soft: #4a4738;
        --line: #17150f; --acid: #b6ff00; --acid-ink: #5f7a00;
        --a1: #0e6e91; --a1-bg: #d8ecf4; --a2: #c4006b; --a2-bg: #fadbeb;
        --a3: #1f7a3d; --a3-bg: #dff0d9; --a4: #b54a00; --a4-bg: #fbe4d2;
        --gate: #8a6d00; --gate-bg: #fff3c4; --warn: #a3341a; --warn-bg: #fbe0d8;
        --card: #faf8f3; --shadow: rgba(23, 21, 15, 0.85); --noise: rgba(23, 21, 15, 0.05);
      }
      :root[data-theme="dark"] {
        --paper: #101013; --paper-2: #17171b; --ink: #ececdf; --ink-soft: #a5a293;
        --line: #ececdf; --acid: #b6ff00; --acid-ink: #b6ff00;
        --a1: #3fc3e8; --a1-bg: #0d2530; --a2: #ff4fa8; --a2-bg: #2c0f1f;
        --a3: #4fd07d; --a3-bg: #10271a; --a4: #ff9a4d; --a4-bg: #2b1a0c;
        --gate: #ffd94d; --gate-bg: #292109; --warn: #ff8a66; --warn-bg: #2c1109;
        --card: #17171b; --shadow: rgba(182, 255, 0, 0.28); --noise: rgba(236, 236, 223, 0.04);
      }

      * { box-sizing: border-box; }
      body {
        background: repeating-linear-gradient(0deg, transparent 0 3px, var(--noise) 3px 4px), var(--paper);
        color: var(--ink);
        font-family: "Helvetica Neue", Helvetica, Arial, system-ui, sans-serif;
        font-size: 15px; line-height: 1.5; margin: 0;
      }
      .wrap { max-width: 1040px; margin: 0 auto; padding: 32px 20px 80px; }
      .display {
        font-family: Haettenschweiler, "Arial Narrow", Impact, "Franklin Gothic Medium", sans-serif;
        font-weight: 400; letter-spacing: 0.01em; text-transform: uppercase;
      }
      code, .mono { font-family: ui-monospace, "SF Mono", Menlo, Consolas, monospace; font-size: 0.88em; }

      /* series nav */
      .series { font-family: ui-monospace, Menlo, monospace; font-size: 11px; letter-spacing: 0.14em;
        text-transform: uppercase; color: var(--ink-soft); margin: 0 0 12px; }
      .series b { color: var(--ink); }

      /* hero */
      header { border: 3px solid var(--line); padding: 24px 26px 20px; margin-bottom: 14px;
        position: relative; background: var(--card); box-shadow: 8px 8px 0 var(--shadow); }
      .eyebrow { font-family: ui-monospace, Menlo, Consolas, monospace; font-size: 12px;
        letter-spacing: 0.2em; text-transform: uppercase; color: var(--ink-soft); margin: 0 0 6px; }
      h1 { font-size: clamp(40px, 7vw, 74px); line-height: 0.92; margin: 0; text-wrap: balance; }
      h1 .neon { background: var(--acid); color: #17150f; padding: 0 10px; display: inline-block; transform: rotate(-1.2deg); }
      .lede { max-width: 64ch; color: var(--ink-soft); margin: 14px 0 0; }
      .lede strong { color: var(--ink); }
      .hero-stats { display: flex; flex-wrap: wrap; gap: 0; margin-top: 18px; border: 2px solid var(--line); }
      .hero-stats > div { flex: 1 1 110px; padding: 8px 14px; border-right: 2px solid var(--line); }
      .hero-stats > div:last-child { border-right: none; }
      .hero-stats b { display: block; font-size: 24px;
        font-family: Haettenschweiler, "Arial Narrow", Impact, sans-serif; font-weight: 400; }
      .hero-stats span { font-size: 10.5px; letter-spacing: 0.12em; text-transform: uppercase; color: var(--ink-soft); }

      /* status banner (Proposed ADRs / repo divergence) */
      .status { border: 2px dashed var(--warn); background: var(--warn-bg); color: var(--ink);
        padding: 10px 14px; margin: 14px 0 0; font-size: 12.5px; display: flex; gap: 10px; align-items: baseline; }
      .status b { color: var(--warn); font-family: ui-monospace, Menlo, monospace; letter-spacing: 0.06em;
        text-transform: uppercase; white-space: nowrap; }

      /* frameless pixel sprites */
      .sprite { display: inline-block; vertical-align: middle; line-height: 0; margin-right: 8px; }
      .sprite img { width: 44px; height: 40px; image-rendering: pixelated; display: block; }
      .sprite.big img { width: 88px; height: 80px; }
      .sprite.sm img { width: 33px; height: 30px; }
      .sprite.fr { float: right; margin: 0 0 6px 12px; }

      /* section scaffold */
      h2.sec { font-size: 30px; margin: 40px 0 2px; }
      .sub { font-size: 12px; letter-spacing: 0.14em; text-transform: uppercase; color: var(--ink-soft); margin: 0 0 12px; }

      .card { border: 2px solid var(--line); background: var(--card); padding: 12px 15px; box-shadow: 5px 5px 0 var(--shadow); }
      .card p { margin: 6px 0 0; font-size: 13.5px; color: var(--ink-soft); }
      .card p strong { color: var(--ink); }
      .card h4 { margin: 0; font-size: 18px; }

      .tag { display: inline-block; font-family: ui-monospace, Menlo, Consolas, monospace; font-size: 11.5px;
        font-weight: 700; letter-spacing: 0.04em; padding: 2px 8px; border: 1.5px solid currentColor; }
      .t-1 { color: var(--a1); } .t-2 { color: var(--a2); } .t-3 { color: var(--a3); }
      .t-4 { color: var(--a4); } .t-x { color: var(--ink); }
      .persona { font-size: 12.5px; color: var(--ink-soft); margin-left: 6px; }

      /* numbered flow (render farm loop, detect-correct loop) */
      .flow { position: relative; padding-left: 52px; }
      .flow::before { content: ""; position: absolute; left: 19px; top: 4px; bottom: 4px; width: 4px;
        background: repeating-linear-gradient(180deg, var(--line) 0 13px, transparent 13px 21px); }
      .step { position: relative; margin-bottom: 14px; }
      .step .n { position: absolute; left: -52px; top: -2px; width: 40px; height: 40px; border: 3px solid var(--line);
        background: var(--paper); display: flex; align-items: center; justify-content: center;
        font-family: Haettenschweiler, "Arial Narrow", Impact, sans-serif; font-size: 22px; z-index: 1; }
      .step .n.hot { background: var(--acid); color: #17150f; }
      .step .card { box-shadow: 4px 4px 0 var(--shadow); }

      /* stamp gate */
      .stamp { display: inline-block; border: 3px double var(--gate); color: var(--gate); background: var(--gate-bg);
        font-family: Haettenschweiler, "Arial Narrow", Impact, sans-serif; font-size: 16px; letter-spacing: 0.06em;
        text-transform: uppercase; padding: 3px 12px 2px; transform: rotate(-2deg); white-space: nowrap; }
      .stamp small { display: block; font-family: ui-monospace, Menlo, monospace; font-size: 9px;
        letter-spacing: 0.1em; transform: none; }
      .gate-row { display: flex; align-items: center; gap: 14px; flex-wrap: wrap; margin: 12px 0; }
      .gate-note { font-size: 12.5px; color: var(--ink-soft); flex: 1 1 260px; margin: 0; }
      .loopback { font-family: ui-monospace, Menlo, monospace; font-size: 11px; color: var(--ink-soft);
        border-left: 3px solid var(--gate); padding: 2px 8px; margin-top: 8px; }

      /* generic grids */
      .grid2 { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 12px; }
      .grid3 { display: grid; grid-template-columns: repeat(auto-fit, minmax(210px, 1fr)); gap: 10px; }
      .grid2 .card, .grid3 .card { box-shadow: 3px 3px 0 var(--shadow); font-size: 13px; }
      .grid3 .card b, .grid2 .card b { display: block; margin-bottom: 3px; }
      .mini { font-family: ui-monospace, Menlo, monospace; font-size: 11px; color: var(--ink-soft); }

      /* parallax layer stack (level-art hero) */
      .layers { display: grid; gap: 6px; margin-top: 6px; }
      .layers .lyr { border: 2px solid var(--line); padding: 8px 12px; font-size: 13px; position: relative; overflow: hidden; }
      .layers .lyr b { font-family: ui-monospace, Menlo, monospace; }
      .layers .sky { background: var(--a3-bg); }
      .layers .facade { background: var(--a2-bg); }
      .layers .street { background: var(--a4-bg); }
      .layers .k { float: right; font-family: ui-monospace, Menlo, monospace; font-size: 11px; color: var(--ink-soft); }

      /* defect chips */
      .chips { display: flex; flex-wrap: wrap; gap: 6px; margin-top: 6px; }
      .chip { font-family: ui-monospace, Menlo, monospace; font-size: 11px; border: 1.5px solid var(--warn);
        color: var(--warn); padding: 1px 7px; }

      /* mode cards D1/D2/D3 */
      .modes { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 12px; }
      .mode { border: 2px solid var(--a2); background: var(--card); padding: 12px 14px; box-shadow: 4px 4px 0 var(--shadow); }
      .mode .k { font-family: Haettenschweiler, "Arial Narrow", Impact, sans-serif; font-size: 26px; color: var(--a2); line-height: 1; }
      .mode h4 { margin: 2px 0 4px; font-size: 16px; }
      .mode p { margin: 0; font-size: 12.5px; color: var(--ink-soft); }
      .mode .saw { display: block; font-family: ui-monospace, Menlo, monospace; font-size: 10.5px;
        letter-spacing: 0.06em; text-transform: uppercase; color: var(--a2); margin-bottom: 4px; }

      /* source-of-truth callout */
      .truth { border: 3px solid var(--a3); background: var(--a3-bg); padding: 14px 16px; box-shadow: 6px 6px 0 var(--shadow); }
      .truth h4 { margin: 0 0 4px; font-size: 20px; }
      .truth code { color: var(--ink); }
      .truth .who { float: right; }

      /* two-column reads */
      .io { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
      @media (max-width: 560px) { .io, .modes, .grid2 { grid-template-columns: 1fr; } }

      /* crew strip */
      .crew { display: flex; flex-wrap: wrap; gap: 12px; margin-top: 12px; }
      .crew .m { display: flex; align-items: center; gap: 6px; border: 2px solid var(--line); background: var(--card);
        padding: 6px 10px 6px 6px; font-size: 12.5px; box-shadow: 3px 3px 0 var(--shadow); }
      .crew .m .role { font-family: ui-monospace, Menlo, monospace; font-weight: 700; }
      .crew .m .why { color: var(--ink-soft); }

      footer { margin-top: 44px; font-size: 12px; color: var(--ink-soft); border-top: 2px solid var(--line); padding-top: 12px; }
      footer code { font-size: 11.5px; }
      a { color: inherit; }
    </style>
  </head>
  <body>
    <div class="wrap">
"""

FOOT = """    </div>
  </body>
</html>
"""


def series_nav(active):
    items = [
        ("level-art", "Level-art"),
        ("window-alignment", "Window-align"),
        ("dynamic-verify", "Vérif. dynamique"),
        ("shared-lib", "Lib partagée"),
    ]
    parts = []
    for slug, label in items:
        parts.append(f"<b>{label}</b>" if slug == active else label)
    return '<p class="series">Les harness de muf · ' + " · ".join(parts) + "</p>"


def crew_strip(members):
    """members: list of (slug, role, persona, why)."""
    ms = "".join(
        f'<div class="m">{sprite(slug)}<span><span class="role">{role}</span> '
        f'<span class="persona">{persona}</span><br /><span class="why">{why}</span></span></div>'
        for slug, role, persona, why in members
    )
    return f'<div class="crew">{ms}</div>'


PAGES = []


# ══════════════════════════════════════════════════════════════════════════════
# 1. LEVEL-ART HARNESS
# ══════════════════════════════════════════════════════════════════════════════
level_art = f"""{series_nav("level-art")}
      <header>
        <p class="eyebrow">muf · harness #1 · HARNESS.md</p>
        {sprite("dev-tooling-assets", "big fr", "Amelia — tooling")}
        <h1 class="display">Level-art<br /><span class="neon">harness</span></h1>
        <p class="lede">
          Les niveaux sont <strong>data-driven</strong> : ciel / façade / rue sont de grandes images
          générées par IA, compositées en <strong>couches parallax</strong>. Un manifeste unique décrit
          tout, et une <strong>render farm CI</strong> génère l'art, build le jeu, le screenshote et
          recommite le tout — parce que l'egress réseau est bloqué dans le bac à sable local.
        </p>
        <div class="hero-stats display">
          <div><b>3</b><span>couches parallax</span></div>
          <div><b>1</b><span>manifeste source</span></div>
          <div><b>5</b><span>étapes render farm</span></div>
          <div><b>3840²</b><span>captures (×2160)</span></div>
        </div>
      </header>

      <h2 class="sec display">La source unique</h2>
      <p class="sub">tout lit le même fichier</p>
      <div class="truth">
        {sprite("concept-artist", "fr", "Maud")}
        <h4 class="display">src/game/levels/levelArt.json</h4>
        <p class="mini">style · sizes {{ sky · facade · street }} · levels[] : id · name · label · parallax · prompts</p>
        <p>Lu à la fois par <strong>l'app (rendu)</strong> et par <strong>scripts/gen-level-art.mjs</strong>
          (génération). Ajouter un niveau = <strong>une entrée ici</strong> (+ la map gameplay qui porte les
          slots d'ennemis). Les prompts sont écrits par <span class="tag t-2">concept-artist</span>
          <span class="persona">Maud ✍️</span>, gatés par <span class="tag t-2">lead-art</span>
          <span class="persona">Nico 🎯</span>.</p>
      </div>

      <h2 class="sec display">Les trois couches</h2>
      <p class="sub">facteur parallax k : place la couche à camera.x · k</p>
      <div class="layers">
        <div class="lyr sky"><span class="k">k → 1 · dérive la plus lente</span><b>sky</b> — le ciel lointain, quasi épinglé à la vue</div>
        <div class="lyr facade"><span class="k">k = 0 · world-locked</span><b>facade</b> — la façade, verrouillée au monde (les fenêtres = slots de flics)</div>
        <div class="lyr street"><span class="k">k ≈ 0.04</span><b>street</b> — la rue au premier plan</div>
      </div>

      <h2 class="sec display">Générer l'art</h2>
      <div class="grid2">
        <div class="card"><b class="t-1">En local (souvent à vide)</b>
          <code>node scripts/gen-level-art.mjs</code> (manquants) · <code>--force</code> (tout).
          Images tirées de <strong>pollinations.ai (FLUX)</strong> → <code>public/assets/levels/&lt;id&gt;/{{sky,facade,street}}.png</code>.
          L'egress est généralement <strong>bloqué en sandbox</strong> — la génération se fait donc en CI.</div>
        <div class="card"><b class="t-1">Dev sans art</b>
          <code>yarn dev</code> tourne <strong>sans aucune image</strong> : <code>LevelBackdrop</code> retombe sur
          des aplats de couleur quand les PNG manquent. Pull la branche après un run CI pour récupérer l'art committé.</div>
      </div>

      <h2 class="sec display">La render farm</h2>
      <p class="sub">.github/workflows/preview.yml — vrai Chromium avec WebGL, que le sandbox local n'a pas</p>
      <div class="flow">
        <div class="step"><div class="n display">1</div><div class="card">{sprite("dev-tooling-assets", "sm")}<strong>Générer</strong> l'art de niveau manquant (IA, pollinations FLUX).</div></div>
        <div class="step"><div class="n display">2</div><div class="card"><code>yarn build</code> — compile le jeu.</div></div>
        <div class="step"><div class="n display">3</div><div class="card">{sprite("dev-r3f-render", "sm")}<strong>Piloter le jeu buildé headless</strong> et screenshoter le menu + <strong>chaque niveau</strong> en 3840×2160, après 15 s d'attente pour que les flics apparaissent.</div></div>
        <div class="step"><div class="n display">4</div><div class="card">Stitcher une <strong>contact sheet</strong> <code>screenshots/overview.png</code>.</div></div>
        <div class="step"><div class="n hot display">5</div><div class="card"><strong>Recommiter</strong> <code>public/assets/levels/</code> + <code>screenshots/</code> sur la branche.</div></div>
      </div>
      <p class="mini">Déclenchement : push sur la branche, ou Actions → Run workflow → <code>regenerate = true</code> pour rouler des variantes fraîches.</p>

      <h2 class="sec display">Aligner les fenêtres de flics</h2>
      <div class="card">
        {sprite("dev-r3f-render", "fr", "Amelia — render")}
        <p style="margin-top:0">Les façades IA n'ont pas de grille propre, donc une grille fixe fait déborder les flics
          ou les pose sur le mur nu. Deux outils gardent les <strong>window zones</strong>
          (<code>windowZones.generated.json</code>) honnêtes :</p>
        <p><code>gen-window-zones.mjs</code> snappe la grille sur la lumière chaude des fenêtres ·
          <code>align-windows.mjs</code> est le <strong>harness detect-and-correct</strong> (voir l'infographie dédiée),
          avec <code>--check</code> comme gate CI.</p>
      </div>

      <h2 class="sec display">Le crew sur ce harness</h2>
      {crew_strip([
        ("dev-tooling-assets", "dev-tooling-assets", "Amelia 🛠️", "possède le harness, les scripts gen-*, la render farm CI"),
        ("dev-r3f-render", "dev-r3f-render", "Amelia 🎨", "rend les couches parallax du levelArt (HARNESS.md)"),
        ("concept-artist", "concept-artist", "Maud ✍️", "écrit les prompts sky/facade/street dans levelArt.json"),
        ("lead-art", "lead-art", "Nico 🎯", "gate les prompts et l'art généré"),
        ("art-advisor", "art-advisor", "Estelle 📼", "ancrage des références (Paris 1998)"),
      ])}

      <footer>
        Source : <code>HARNESS.md</code> · <code>docs/ci.md</code> · <code>docs/asset-pipeline.md</code>.
        Un poster de la série des harness de muf. Sprites : <code>docs/muf-crew-bitmap.py --singles</code>.
      </footer>
"""
PAGES.append(("harness-level-art-infographic.html", "muf — Level-art harness", level_art))


# ══════════════════════════════════════════════════════════════════════════════
# 2. WINDOW-ALIGNMENT HARNESS
# ══════════════════════════════════════════════════════════════════════════════
window_align = f"""{series_nav("window-alignment")}
      <header>
        <p class="eyebrow">muf · harness #2 · align-windows.mjs · ADR-0028</p>
        {sprite("dev-tooling-assets", "big fr", "Amelia — tooling")}
        <h1 class="display">Window-align<br /><span class="neon">harness</span></h1>
        <p class="lede">
          Les façades IA n'ont pas de grille propre : une grille fixe fait <strong>déborder</strong> les flics de
          leur fenêtre, en pose sur le <strong>mur nu</strong>, et laisse de vraies fenêtres allumées sans personne
          devant. Ce harness <strong>détecte les vraies fenêtres</strong> depuis l'art, puis pilote le rendu réel
          en boucle jusqu'à placer <strong>un flic non-débordant par fenêtre</strong>.
        </p>
        <div class="hero-stats display">
          <div><b>4</b><span>types de défaut</span></div>
          <div><b>≤12</b><span>itérations</span></div>
          <div><b>88%</b><span>remplissage cible</span></div>
          <div><b>0</b><span>défaut = succès</span></div>
        </div>
      </header>

      <h2 class="sec display">Entrées / sortie</h2>
      <div class="io">
        <div class="card"><b class="t-3">Lit</b>
          <code>public/assets/levels/&lt;id&gt;/facade.png</code> · la bande de jeu <code>windowGrid.top/bottom</code>
          et le tuning par niveau dans <code>levelArt.json</code>.</div>
        <div class="card"><b class="t-1">Écrit</b>
          <code>windowZones.generated.json</code> — <strong>uniquement la clé du niveau ciblé</strong>
          (<code>belliard</code> / <code>stalingrad</code> / <code>vitry</code>) ; les autres restent octet pour octet
          identiques. Preuve : overlays <code>.dbg-&lt;id&gt;-align-*.jpg</code> (gitignorés).</div>
      </div>

      <h2 class="sec display">La boucle detect-and-correct</h2>
      <p class="sub">détecter · piloter · mesurer · corriger — jusqu'à 0 défaut</p>
      <div class="flow">
        <div class="step"><div class="n display">1</div><div class="card"><strong>Détecter les vraies fenêtres</strong> de la façade.
          Étages : <code>belliard</code> = <strong>tiers égaux</strong> (préserve son résultat livré) ; autres niveaux =
          <strong>détection run-based</strong> par étage (robuste à tout nombre d'étages). Les fenêtres sombres/ambiguës
          ne sont jamais inventées.</div></div>
        <div class="step"><div class="n display">2</div><div class="card">{sprite("dev-r3f-render", "sm")}<strong>Piloter le rendu prod live</strong> headless
          (SwiftShader, un flic statique figé par slot) : pousser les zones candidates via <code>window.__MUF_ZONES__</code> + <code>__MUF_APPLY_ZONES__()</code>.</div></div>
        <div class="step"><div class="n display">3</div><div class="card"><strong>Lire</strong> chaque boîte de sprite rendue via
          <code>__MUF_SLOT_RECTS__()</code>. Le mapping hauteur → (taille, y) est calibré sur le premier rendu.</div></div>
        <div class="step"><div class="n display">4</div><div class="card"><strong>Placer un flic non-débordant par fenêtre</strong> :
          régler <code>zone.h</code> (sprite ≈ 88 % de la hauteur d'ouverture) et <code>zone.y</code>, appariement 1:1 zones ↔ ouvertures.</div></div>
        <div class="step"><div class="n hot display">5</div><div class="card"><strong>Mesurer et corriger en boucle</strong> (max 12 itérations)
          jusqu'à <strong>0 défaut</strong> ; overlay de preuve à chaque tour. N'écrit que si convergé.</div></div>
      </div>

      <h2 class="sec display">Les quatre défauts</h2>
      <div class="chips">
        <span class="chip">OVERFLOW — sprite ⊄ ouverture</span>
        <span class="chip">COUNT — nb zones ≠ nb fenêtres</span>
        <span class="chip">EMPTY — fenêtre sans zone</span>
        <span class="chip">WALL — zone sur mur nu</span>
      </div>

      <div class="gate-row">
        {sprite("qa-lead")}
        <span class="stamp">Gate CI<small>--check · qa-lead · Inès 🧪</small></span>
        <p class="gate-note"><code>--check</code> = mesure seule : applique les zones committées, lit les rects rendus,
          rapporte les défauts, <strong>n'écrit rien</strong>, exit non-zéro sur tout défaut.
          <code>--fix</code> (défaut) détecte, corrige, écrit. Le JSON est bundlé au build → rebuild avant un check.</p>
      </div>
      <p class="mini"><code>yarn align</code> · <code>yarn align:check</code> · <code>yarn align:belliard[:check]</code></p>

      <h2 class="sec display">Data-driven vs grille fixe</h2>
      <div class="grid3">
        <div class="card"><b>belliard</b><span class="mini">21 → 17 slots (5/5/7) · ~3 étages</span></div>
        <div class="card"><b>stalingrad</b><span class="mini">21 → 12 slots (3/5/4) · ~3 étages</span></div>
        <div class="card"><b>vitry</b><span class="mini">20 → 36 slots · ~8 étages HLM denses</span></div>
      </div>
      <p class="mini">Le nombre d'étages n'est jamais présumé · tolérance containment τ = 0.01 · 3 hooks
        <code>window.__MUF_*</code> dev-only, inertes en production.</p>

      <h2 class="sec display">Le crew sur ce harness</h2>
      {crew_strip([
        ("dev-tooling-assets", "dev-tooling-assets", "Amelia 🛠️", "possède le harness : détection image, boucle, gate CI"),
        ("dev-r3f-render", "dev-r3f-render", "Amelia 🎨", "les hooks __MUF_ZONES__/__MUF_SLOT_RECTS__ vivent dans le rendu"),
        ("lead-art", "lead-art", "Nico 🎯", "sign-off densité : chaque flic cadre une vraie fenêtre"),
        ("game-graphist", "game-designer", "Serge 🕹️", "sign-off : moins de flics simultanés reste mécaniquement sûr"),
        ("qa-lead", "qa-lead", "Inès 🧪", "le gate --check + overlays de preuve = l'artefact de vérification"),
      ])}

      <footer>
        Source : <code>docs/adr/0028-window-alignment-harness.md</code> · <code>scripts/align-windows.mjs</code> ·
        <code>scripts/SCRIPTS.md</code>. Un poster de la série des harness de muf.
        Sprites : <code>docs/muf-crew-bitmap.py --singles</code>.
      </footer>
"""
PAGES.append(("harness-window-alignment-infographic.html", "muf — Window-alignment harness", window_align))


# ══════════════════════════════════════════════════════════════════════════════
# 3. DYNAMIC VERIFICATION HARNESS (ADR-0005, Accepted (amended))
# ══════════════════════════════════════════════════════════════════════════════
dynamic = f"""{series_nav("dynamic-verify")}
      <header>
        <p class="eyebrow">muf · harness #3 · ADR-0005</p>
        {sprite("qa-lead", "big fr", "Inès")}
        <h1 class="display">Vérification<br /><span class="neon">dynamique</span></h1>
        <p class="lede">
          Playwright pilote un vrai Chromium headless (WebGL logiciel), lance le jeu buildé et capture des
          screenshots. L'ADR-0005 le fait passer d'un <strong>preview artifact-only</strong> — qui peut échouer
          invisiblement — à un <strong>merge gate</strong> qui bloque le merge s'il est rouge, en ajoutant trois
          modes de capture qui voient ce que la frame statique ne voyait pas.
        </p>
        <div class="hero-stats display">
          <div><b>3</b><span>modes additifs</span></div>
          <div><b>1</b><span>seam autorisé</span></div>
          <div><b>0</b><span>règle de jeu dans le harness</span></div>
          <div><b>3840²</b><span>px par shot</span></div>
        </div>
        <div class="status"><b>ADR Accepted (amended)</b><span>Statut accepté (2026-07-18) : le pin de <code>preview.yml</code>
          a été élargi (le harness tourne désormais sur <code>claude/**</code> + PR), les trois modes sont livrés et câblés
          en <strong>required check</strong> dans <code>ci.yml</code>. Amendement : D1/D2 re-scopés sur le réel livré
          (la voiture drive-by est retirée, le hostage_taker de rue est devenu le QTE cinématique).</span></div>
      </header>

      <h2 class="sec display">Les trois modes de capture</h2>
      <p class="sub">additifs, non destructifs : le chemin statique gelé reste byte-identique</p>
      <div class="modes">
        <div class="mode"><div class="k display">D1</div><span class="saw">voyait pas : le mouvement</span>
          <h4>Motion capture</h4>
          <p>Séquence multi-frames (strip) des entités de rue livrées : la traversée du livreur (courier) et le QTE
            cinématique — le push de zoom sur l'ancre, puis le tell G4 <code>COVERED→PEEKING</code>. Mode « play »
            dégelé (<code>__MUF_PLAY__</code>), audio muet, seed épinglé ; garde de seam non-vacuité via
            <code>__MUF_STATE__</code>.</p></div>
        <div class="mode"><div class="k display">D2</div><span class="saw">voyait pas : la boucle interactive</span>
          <h4>Play-through scripté</h4>
          <p>Injecte un vrai input dans le canvas, lit l'état LIVE via le seam, assert des deltas exacts :
            belliard PANIC (un tir en ZOOMING → énergie −6, score inchangé) et vitry ACCOMPLICE (sans tirer,
            drain −8 par tir de l'accomplice, <code>captorHp</code> intact — invariant P3-ACC).
            La boucle complète <code>input → render → state → HUD</code>.</p></div>
        <div class="mode"><div class="k display">D3</div><span class="saw">voyait pas : les régressions gelées</span>
          <h4>Golden-screenshot</h4>
          <p>Pixel-diff de <code>stalingrad</code> et <code>vitry</code> contre des goldens PNG committés.
            Garantit au niveau visuel le « byte-for-byte unchanged for the same seed ». Un diff hors tolérance
            rougit le run.</p></div>
      </div>

      <h2 class="sec display">La loi : le seam est la loi</h2>
      <div class="card">
        {sprite("dev-r3f-render", "fr", "Amelia — render")}
        <p style="margin-top:0">Le harness lit l'état de jeu <strong>uniquement</strong> via un seam sanctionné : un getter
          read-only exposé sur <code>window</code> (clone gelé de l'état + HUD), bridgé dans le seul fichier autorisé
          <code>src/hooks/useGameLoop.ts</code>.</p>
        <p><strong>Boundary rule + DIP</strong> : le harness dépend de l'abstraction, jamais d'un import d'un système de
          jeu (<code>src/game/**</code>) ni des internals de rendu (<code>src/render/**</code>) ; il porte zéro règle de jeu.
          <strong>TDD</strong> : les assertions D2 sont écrites en premier, vérifiées à vide, puis vertes contre le build ;
          un harness rouge <strong>bloque le merge</strong>.</p>
      </div>

      <h2 class="sec display">Entrées / sorties</h2>
      <div class="io">
        <div class="card"><b class="t-3">Entrées</b>
          jeu buildé servi à <code>PREVIEW_URL</code> · points de capture <code>?preview=title|menu|narrative|tutorial|end</code> ·
          liste des niveaux depuis <code>levelArt.json</code> · input scripté (D2) · goldens committés (D3).</div>
        <div class="card"><b class="t-1">Sorties</b>
          <code>screenshots/golden/*.png</code> (baselines D3) · strip de frames labellisées via
          <code>stitchLabeledStrip</code> (D1) · verdict d'assertions live (D2) · diff pixel (D3).</div>
      </div>

      <div class="gate-row">
        {sprite("qa-lead")}
        <span class="stamp">Merge gate<small>required check · qa-lead · Inès 🧪</small></span>
        <p class="gate-note">De <strong>artifact-only</strong> (peut échouer invisiblement) à <strong>required check</strong>
          qui bloque. Tension : la flakiness bloque désormais les merges — le déterminisme du mode play (seed fixe, audio
          muet) doit être solide, et le golden churn distingué d'une régression (revue à l'œil en PR).</p>
      </div>

      <h2 class="sec display">Le crew sur ce harness</h2>
      {crew_strip([
        ("qa-lead", "qa-lead", "Inès 🧪", "le harness EST un test : assertions D2 d'abord, gate qui bloque"),
        ("dev-tooling-assets", "dev-tooling-assets", "Amelia 🛠️", "scripts Playwright, contact sheet, câblage required check"),
        ("dev-r3f-render", "dev-r3f-render", "Amelia 🎨", "le seam useGameLoop, WebGL sous SwiftShader, goldens stables"),
        ("lead-art", "lead-art", "Nico 🎯", "revue à l'œil de D1 + arbitrage du golden churn D3"),
      ])}

      <footer>
        Source : <code>docs/adr/0005-dynamic-verification-harness.md</code> (Accepted (amended)) ·
        <code>scripts/harness-motion.mjs</code> · <code>scripts/harness-assert.mjs</code> ·
        <code>scripts/harness-golden.mjs</code> · <code>scripts/e2e-lib.mjs</code>.
        Un poster de la série des harness de muf. Sprites : <code>docs/muf-crew-bitmap.py --singles</code>.
      </footer>
"""
PAGES.append(("harness-dynamic-verify-infographic.html", "muf — Dynamic verification harness", dynamic))


# ══════════════════════════════════════════════════════════════════════════════
# 4. SHARED HARNESS LIBRARY (ADR-0007, Accepted)
# ══════════════════════════════════════════════════════════════════════════════
shared = f"""{series_nav("shared-lib")}
      <header>
        <p class="eyebrow">muf · harness #4 · ADR-0007</p>
        {sprite("senior-architect", "big fr", "Winston")}
        <h1 class="display">Lib de harness<br /><span class="neon">partagée</span></h1>
        <p class="lede">
          Six générateurs <code>.mjs</code> réimplémentent chacun les mêmes blocs (fetch+retry, garde idempotente,
          parsing CLI, cutout). L'ADR-0007 tranche : une <strong>lib de petites primitives pures</strong> sous
          <code>scripts/lib/</code> — et un <strong>refus explicite du méta-harness</strong>, ce « générateur de
          générateurs » qui multiplierait le boilerplate au lieu de le supprimer.
        </p>
        <div class="hero-stats display">
          <div><b>~4</b><span>blocs dupliqués</span></div>
          <div><b>6+</b><span>générateurs concernés</span></div>
          <div><b>13</b><span>consommateurs réels</span></div>
          <div><b>0</b><span>méta-harness</span></div>
        </div>
        <div class="status"><b>ADR Accepted</b><span>Statut accepté (2026-07-18). Les primitives pures sont extraites et
          testées : <code>pollinations.mjs</code>, <code>idempotent.mjs</code>, <code>cli.mjs</code>, <code>cutout.mjs</code>
          (chromaKey prouvé byte-identique sur les 22 PNG enemy) et <code>contact-sheet.mjs</code>, plus le
          <code>_template.mjs</code> copiable. Adoption bornée aux générateurs canoniques ; les scripts legacy sont laissés
          en candidats-retrait.</span></div>
      </header>

      <h2 class="sec display">La décision : refuser le méta-harness</h2>
      <div class="card" style="border-color: var(--warn)">
        {sprite("senior-architect", "fr", "Winston")}
        <p style="margin-top:0"><strong>On ne construit pas un « harness qui génère des harness ».</strong>
          Le mot d'ordre de l'ADR :</p>
        <p style="font-size:15px; color:var(--ink)"><em>« Une couche qui émet du code ne supprime pas le boilerplate —
          elle le multiplie plus vite et le cache derrière un template. »</em></p>
        <p>Abstraction prématurée (anti-YAGNI) <strong>et</strong> fuyante (anti-SOLID) : figée sur la forme d'aujourd'hui
          (« fetch un PNG statique depuis Pollinations »), elle induirait en erreur le prochain harness qui ne partage pas
          cette forme. À la place : des primitives pures importées à la carte, + au plus une <em>anatomie de harness</em>
          documentée et un <code>_template.mjs</code> copié à la main. « Un checklist guide, un générateur ossifie. »</p>
      </div>

      <h2 class="sec display">Les primitives</h2>
      <div class="grid2">
        <div class="card"><b class="t-3">Extrait &amp; testé</b>
          <code>pollinations.mjs</code> fetchWithRetry · <code>idempotent.mjs</code> skipIfExists ·
          <code>cli.mjs</code> parseAssetArgs · <code>cutout.mjs</code> chromaKey (pur, byte-identique dans
          <code>cutout-enemies.mjs</code>) · <code>morphology.mjs</code> (morphologie binaire pure) ·
          <code>_template.mjs</code> (copié à la main, jamais exécuté).</div>
        <div class="card"><b class="t-4">Laissé local à dessein</b>
          Le flood enclosed-island + l'échantillonnage couleur par composant restent dans <code>cutout-enemies.mjs</code>
          (fusionnés, ne se réduisent pas à une primitive pure) · le keyage ratio <code>isMagenta</code> de
          <code>cutout-foreground.mjs</code> (primitive différente, divergerait sur art frais) · <code>e2e-lib.mjs</code>
          reste la lib E2E de facto (seedPlay/readState, <code>stitchLabeledStrip</code>). Le
          <code>contact-sheet.mjs</code> projeté n'est pas construit (YAGNI : un seul consommateur).</div>
      </div>

      <h2 class="sec display">Le principe</h2>
      <div class="grid3">
        <div class="card"><b>DRY mesuré à la source</b>Le doublon EST le problème ; le correctif <strong>supprime</strong>
          du code. Un méta-harness ré-émet des copies fraîches — DRY empire.</div>
        <div class="card"><b>SOLID</b>Chaque harness importe <strong>à la carte</strong> les pièces qu'il partage
          vraiment (SRP), dépend de l'abstraction (DIP), s'étend en important (OCP) — pas un squelette figé.</div>
        <div class="card"><b>TDD</b>Extraire des primitives <strong>pures</strong> rend la tooling testable ;
          tests écrits en premier (rouge) pour chromaKey, skipIfExists, fetchWithRetry.</div>
      </div>

      <h2 class="sec display">Qui consomme la lib</h2>
      <div class="io">
        <div class="card"><b class="t-1">Aujourd'hui (13)</b>
          <span class="mini">morphology.mjs (6) : fill-sprite-holes, retouch-flash-halos, restore-figure-bites,
          fill-bust-hem, check-sprite-integrity, measure-muzzle-anchors · e2e-lib.mjs (7) : e2e-home, e2e-ingame,
          e2e-delivery, e2e-assets, screenshot-preview, preview-vehicle-halo, align-windows</span></div>
        <div class="card"><b class="t-2">Adoption livrée</b>
          <span class="mini">générateurs canoniques (gen-enemy-types, gen-vehicle-sprites, gen-courier-sprites,
          gen-level-art) importent idempotent/cli ; <code>cutout-enemies.mjs</code> importe cutout. Legacy
          (generate-assets, generate-game-assets, regen-pixel-sprites, generate-style-demo) laissés en
          candidats-retrait. Le harness de vérif (ADR-0005) stitche via <code>e2e-lib.mjs</code>.</span></div>
      </div>

      <h2 class="sec display">Le crew sur ce harness</h2>
      {crew_strip([
        ("senior-architect", "senior-architect", "Winston 🏗️", "propriétaire de la décision : arbitrage méta-harness, 4 principes"),
        ("dev-tooling-assets", "dev-tooling-assets", "Amelia 🛠️", "exécutante : extraction des primitives, refactor, tests TDD"),
        ("dev-r3f-render", "dev-r3f-render", "Amelia 🎨", "consommateur aval : le harness de vérif prouve pourquoi le squelette figé serait mauvais"),
      ])}

      <footer>
        Source : <code>docs/adr/0007-shared-harness-library.md</code> (Accepted) · <code>scripts/lib/cutout.mjs</code> ·
        <code>scripts/lib/idempotent.mjs</code> · <code>scripts/lib/cli.mjs</code>. Un poster de la série des harness de muf.
        Sprites : <code>docs/muf-crew-bitmap.py --singles</code>.
      </footer>
"""
PAGES.append(("harness-shared-lib-infographic.html", "muf — Shared harness library", shared))


# ── Emit ────────────────────────────────────────────────────────────────────────
def main():
    for fname, title, body in PAGES:
        html = HEAD.replace("__TITLE__", title) + body + FOOT
        with open(os.path.join(OUT_DIR, fname), "w") as f:
            f.write(html)
        print(f"wrote {fname}")


if __name__ == "__main__":
    main()
