import type { TileMap } from "@game/types/tileMap";

/**
 * Stalingrad — 19e arrondissement
 * Immeuble haussmannien dégradé, fenêtres nombreuses, balcons.
 * 24 colonnes × 5 rangées
 */
export const STALINGRAD_19: TileMap = {
  name: "Stalingrad — 19e",
  cols: 24,
  rows: 5,
  tileW: 1,
  tileH: 1,
  tiles: [
    // row 0 — toiture
    [
      "ROOFTOP",
      "ROOFTOP",
      "ROOFTOP",
      "ROOFTOP",
      "ROOFTOP",
      "ROOFTOP",
      "ROOFTOP",
      "ROOFTOP",
      "ROOFTOP",
      "ROOFTOP",
      "ROOFTOP",
      "ROOFTOP",
      "ROOFTOP",
      "ROOFTOP",
      "ROOFTOP",
      "ROOFTOP",
      "ROOFTOP",
      "ROOFTOP",
      "ROOFTOP",
      "ROOFTOP",
      "ROOFTOP",
      "ROOFTOP",
      "ROOFTOP",
      "ROOFTOP",
    ],
    // row 1 — étage 3
    [
      "WALL",
      "WINDOW_DARK",
      "WALL",
      "WINDOW_LIT",
      "WALL",
      "WINDOW_DARK",
      "WALL",
      "WINDOW_DARK",
      "WALL",
      "WINDOW_LIT",
      "WALL",
      "WINDOW_DARK",
      "WALL",
      "WINDOW_LIT",
      "WALL",
      "WINDOW_DARK",
      "WALL",
      "WINDOW_LIT",
      "WALL",
      "WINDOW_DARK",
      "WALL",
      "WINDOW_LIT",
      "WALL",
      "WALL",
    ],
    // row 2 — étage 2
    [
      "WALL",
      "WINDOW_LIT",
      "WALL",
      "WINDOW_DARK",
      "WALL",
      "WINDOW_LIT",
      "WALL",
      "WINDOW_DARK",
      "WALL",
      "WINDOW_LIT",
      "WALL",
      "WINDOW_DARK",
      "WALL",
      "WINDOW_DARK",
      "WALL",
      "WINDOW_LIT",
      "WALL",
      "WINDOW_DARK",
      "WALL",
      "WINDOW_LIT",
      "WALL",
      "WINDOW_DARK",
      "WALL",
      "WALL",
    ],
    // row 3 — étage 1
    [
      "WALL",
      "WINDOW_DARK",
      "WALL",
      "WINDOW_LIT",
      "WALL",
      "WINDOW_DARK",
      "WALL",
      "WINDOW_LIT",
      "WALL",
      "WINDOW_DARK",
      "WALL",
      "WINDOW_LIT",
      "WALL",
      "WINDOW_DARK",
      "WALL",
      "WINDOW_LIT",
      "WALL",
      "WINDOW_DARK",
      "WALL",
      "WINDOW_LIT",
      "WALL",
      "WINDOW_DARK",
      "WALL",
      "WALL",
    ],
    // row 4 — rez-de-chaussée
    [
      "WALL",
      "DOOR",
      "WALL",
      "WALL",
      "WALL",
      "WINDOW_DARK",
      "WALL",
      "WALL",
      "WALL",
      "DOOR",
      "WALL",
      "WALL",
      "WALL",
      "WINDOW_DARK",
      "WALL",
      "WALL",
      "WALL",
      "DOOR",
      "WALL",
      "WALL",
      "WALL",
      "WINDOW_DARK",
      "WALL",
      "WALL",
    ],
  ],
};
